# Generated by Django 4.2.8 on 2023-12-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stu.clazz')),
            ],
        ),
    ]
