# Generated by Django 4.2.8 on 2023-12-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 't_course',
            },
        ),
    ]
