# Generated by Django 4.2.8 on 2023-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=30)),
                ('course', models.ManyToManyField(to='stu3.course')),
            ],
            options={
                'db_table': 't_stu3',
            },
        ),
    ]
