# Generated by Django 4.2.8 on 2023-12-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clazz',
            options={'verbose_name_plural': 'Class table'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student table'},
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='stu.clazz', verbose_name='Class belong'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clazz',
            name='cname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Class Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sname',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Student Number'),
        ),
    ]
